# Generated by Django 4.2.30 on 2026-06-03 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageBackend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('backend_type', models.CharField(choices=[('s3', 'S3 / MinIO'), ('gdrive', 'Google Drive'), ('github', 'GitHub'), ('webdav', 'WebDAV'), ('irods', 'iRODS'), ('local', 'Local filesystem')], max_length=20)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('error', 'Error'), ('syncing', 'Syncing'), ('unreachable', 'Unreachable')], default='syncing', max_length=20)),
                ('endpoint_url', models.CharField(blank=True, max_length=512)),
                ('root_path', models.CharField(blank=True, max_length=512)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('virtual_lab', models.CharField(blank=True, max_length=255)),
                ('dataset_count', models.PositiveIntegerField(default=0)),
                ('total_size_bytes', models.BigIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vrefs_storage_backends',
                'ordering': ['-created_at'],
            },
        ),
    ]
