# Generated by Django 4.2.30 on 2026-06-03 09:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pid_type', models.CharField(choices=[('internal', 'Internal (dl:)'), ('doi', 'DataCite DOI'), ('handle', 'Handle')], max_length=20)),
                ('pid_value', models.CharField(max_length=512, unique=True)),
                ('resolver_url', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pids', to='datasets.dataset')),
            ],
            options={
                'db_table': 'vrefs_pids',
            },
        ),
    ]
