# Generated by Django 4.2.30 on 2026-06-03 09:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagedDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_by', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('copying', 'Copying'), ('ready', 'Ready'), ('expired', 'Expired'), ('error', 'Error')], default='pending', max_length=20)),
                ('staged_bucket', models.CharField(blank=True, max_length=255)),
                ('staged_key', models.CharField(blank=True, max_length=1024)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('workflow_run_id', models.CharField(blank=True, max_length=255)),
                ('dataset_version', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_copies', to='datasets.dataset')),
            ],
            options={
                'db_table': 'vrefs_staged_datasets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dataset', 'status'], name='vrefs_stage_dataset_97597a_idx'), models.Index(fields=['expires_at'], name='vrefs_stage_expires_e7ad95_idx')],
            },
        ),
    ]
